name: GitHub to Tencent COS Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-cos:
    name: Sync to Tencent COS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Rclone
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      # Sync to Tencent COS
      - name: Rclone Sync
        run: |
          rclone sync ./ TencentCOS:${{ secrets.COS_BUCKET }} --transfers=8 --checkers=16 --exclude=.git/** --exclude=.github/** --exclude=README.md
        env:
          RCLONE_CONFIG_PASS: ${{ secrets.RCLONE_CONFIG_PASS }}
