name: GitHub to Alibaba OSS Sync  

on:  
  push:  
    branches:  
      - main  
  workflow_dispatch:  

jobs:  
  sync-to-oss:  
    name: Sync to Alibaba OSS  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v3  

      - name: Configure Rclone  
        run: |  
          curl https://rclone.org/install.sh | sudo bash
          echo "[aliyunoss]" > /tmp/rclone.conf  
          echo "type = s3" >> /tmp/rclone.conf  
          echo "provider = Alibaba" >> /tmp/rclone.conf  
          echo "access_key_id = ${{ secrets.ALIYUN_ACCESS_KEY_ID }}" >> /tmp/rclone.conf  
          echo "secret_access_key = ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}" >> /tmp/rclone.conf  
          echo "endpoint = ${{ secrets.ALIYUN_REGION }}.aliyuncs.com" >> /tmp/rclone.conf
 
      - name: Rclone Sync  
        run: |  
          rclone --config /tmp/rclone.conf sync ./ aliyunoss:${{ secrets.ALIYUN_BUCKET }} --no-update-modtime --transfers=8 --checkers=16 --exclude=.git/** --exclude=.github/** --exclude=README.md -v
          rm -f /tmp/rclone.conf